### ISSUE TITLE
Syntax Error on Feature Extraction

### ISSUE THREAD

**Issue by rzamarefat** [naver/deep-image-retrieval#37]
Hi Thank you for this awesome implementation. I have used the following command:

```
python dirtorch/extract_features.py --dataset /mnt/829A20D99A20CB8B/projects/Datasets/Products_Digi/images/shoe --checkpoint /mnt/829A20D99A20CB8B/projects/deep-image-retrieval/Resnet101-TL-GeM.pt --output /mnt/829A20D99A20CB8B/projects/deep-image-retrieval/features.txt --gpu 0 --whiten Landmarks_clean --whitenp 0.25
```
This command is exactly based on your instructions. However I got the following error:
```
Traceback (most recent call last):
  File "dirtorch/extract_features.py", line 111, in <module>
    dataset = datasets.create(args.dataset)
  File "/mnt/829A20D99A20CB8B/projects/deep-image-retrieval/dirtorch/datasets/create.py", line 24, in __call__
    return eval(dataset_cmd)
  File "<string>", line 1
    /mnt/829A20D99A20CB8B/projects/Datasets/Products_Digi/images/shoe()
    ^
SyntaxError: invalid syntax
```

**Comment by baoloc97** [comment]
the dataset param need a function like ImageList, Dataset ,,vv u can check
